In [2]:
import pandas as pd 
carwash = pd.read_csv("C:/Users/Sung/Desktop/Opinet_Data/주유소_부가정보/carwash.csv", encoding= "cp949")
repair = pd.read_csv("C:/Users/Sung/Desktop/Opinet_Data/주유소_부가정보/repair.csv", encoding= "cp949")
conv_store = pd.read_csv("C:/Users/Sung/Desktop/Opinet_Data/주유소_부가정보/conv_store.csv", encoding= "cp949")
all247 = pd.read_csv("C:/Users/Sung/Desktop/Opinet_Data/주유소_부가정보/all247.csv", encoding= "cp949")

* wash_yn
* repair_yn
* conv_yn
* all24_yn

In [3]:
# carwash 
del carwash["Unnamed: 0"]
del carwash["repair_yn"]
del carwash["conv_yn"]
del carwash["all24_yn"]

In [4]:
# repair 
del repair["Unnamed: 0"]
del repair["wash_yn"]
del repair["conv_yn"]
del repair["all24_yn"]

In [5]:
# conv_store
del conv_store["Unnamed: 0"]
del conv_store["wash_yn"]
del conv_store["repair_yn"]
del conv_store["all24_yn"]

In [6]:
# all247
del all247["Unnamed: 0"]
del all247["wash_yn"]
del all247["repair_yn"]
del all247["conv_yn"]

In [8]:
del carwash["oil_price"]
del repair["oil_price"]
del conv_store["oil_price"]
del all247["oil_price"]

In [9]:
carwash.columns

Index(['sido', 'si', 'gu', 'os_nm', 'new_adr', 'api_adr', 'poll_div_cd',
       'self_yn', 'wash_yn'],
      dtype='object')

In [17]:
merge_dat1 = pd.merge(carwash, repair, how = "outer",
                     left_on = ["sido", "si", "gu","os_nm","new_adr","api_adr","poll_div_cd","self_yn"], 
                     right_on = ["sido", "si", "gu","os_nm","new_adr","api_adr","poll_div_cd","self_yn"])

In [18]:
merge_dat1

,sido,si,gu,os_nm,new_adr,api_adr,poll_div_cd,self_yn,wash_yn,repair_yn
0,서울특별시,서울,강남구,(주)보성 세곡주유소,서울 강남구 헌릉로 731 (세곡동),서울 강남구 헌릉로 731,SK에너지,Y,Y,NaN
1,서울특별시,서울,강남구,오일프러스 셀프,서울 강남구 남부순환로 2651 (도곡동),서울 강남구 남부순환로 2651,SK에너지,Y,Y,Y
2,서울특별시,서울,강남구,현대오일뱅크 도곡셀프주유소,서울 강남구 남부순환로 2718 (도곡2동),서울 강남구 남부순환로 2718,현대오일뱅크,Y,Y,Y
3,서울특별시,서울,강남구,GS칼텍스(주)직영 산성주유소,서울 강남구 헌릉로 730,서울 강남구 헌릉로 730,GS칼텍스,Y,Y,NaN
4,서울특별시,서울,강남구,방죽주유소,서울 강남구 밤고개로 215 (율현동),서울 강남구 밤고개로 215,S-OIL,Y,Y,NaN
...,...,...,...,...,...,...,...,...,...,...
7872,울산광역시,울산,울주군,대복주유소,울산 울주군 웅촌면 웅촌로 671,울산 울주군 웅촌면 웅촌로 671,현대오일뱅크,N,NaN,Y
7873,경기도,경기,김포시,한누리주유소,경기 김포시 월곶면 김포대로 2519,경기 김포시 월곶면 김포대로 2519,SK에너지,N,NaN,Y
7874,충청남도,충남,아산시,문방스타주유소,충남 아산시 아산만로 1504,충남 아산시 아산만로 1504,현대오일뱅크,N,NaN,Y
7875,전라북도,전북,남원시,광장주유소,전북 남원시 춘향로 294(용정동),전북 남원시 춘향로 294,현대오일뱅크,N,NaN,Y
7876,전라남도,전남,무안군,서해안주유소,전남 무안군 무안읍 무안로 592,전남 무안군 무안읍 무안로 592,SK에너지,N,NaN,Y

In [13]:
merge_dat2 = pd.merge(conv_store, all247, how = "outer",
                     left_on = ["sido", "si", "gu","os_nm","new_adr","api_adr","poll_div_cd","self_yn"], 
                     right_on = ["sido", "si", "gu","os_nm","new_adr","api_adr","poll_div_cd","self_yn"])

In [22]:
merge_dat1[merge_dat1['wash_yn'].isna()]

,sido,si,gu,os_nm,new_adr,api_adr,poll_div_cd,self_yn,wash_yn,repair_yn
7606,서울특별시,서울,강남구,지에스칼텍스㈜ GS타워주유소,서울 강남구 논현로 516 (역삼동),서울 강남구 논현로 516,GS칼텍스,N,NaN,Y
7607,서울특별시,서울,마포구,SK에너지 양지주유소,서울 마포구 마포대로 69 (도화동),서울 마포구 마포대로 69,SK에너지,N,NaN,Y
7608,서울특별시,서울,송파구,대성석유(주)석촌주유소,서울 송파구 백제고분로 289,서울 송파구 백제고분로 289,GS칼텍스,N,NaN,Y
7609,서울특별시,서울,송파구,제트라인DM주유소,서울 송파구 중대로 183 (가락동),서울 송파구 중대로 183,현대오일뱅크,N,NaN,Y
7610,서울특별시,서울,송파구,송파주유소,서울 송파구 송이로 28 (송파동),서울 송파구 송이로 28,GS칼텍스,Y,NaN,Y
...,...,...,...,...,...,...,...,...,...,...
7872,울산광역시,울산,울주군,대복주유소,울산 울주군 웅촌면 웅촌로 671,울산 울주군 웅촌면 웅촌로 671,현대오일뱅크,N,NaN,Y
7873,경기도,경기,김포시,한누리주유소,경기 김포시 월곶면 김포대로 2519,경기 김포시 월곶면 김포대로 2519,SK에너지,N,NaN,Y
7874,충청남도,충남,아산시,문방스타주유소,충남 아산시 아산만로 1504,충남 아산시 아산만로 1504,현대오일뱅크,N,NaN,Y
7875,전라북도,전북,남원시,광장주유소,전북 남원시 춘향로 294(용정동),전북 남원시 춘향로 294,현대오일뱅크,N,NaN,Y
7876,전라남도,전남,무안군,서해안주유소,전남 무안군 무안읍 무안로 592,전남 무안군 무안읍 무안로 592,SK에너지,N,NaN,Y

In [23]:
merge_dat1[merge_dat1['repair_yn'].isna()]

,sido,si,gu,os_nm,new_adr,api_adr,poll_div_cd,self_yn,wash_yn,repair_yn
0,서울특별시,서울,강남구,(주)보성 세곡주유소,서울 강남구 헌릉로 731 (세곡동),서울 강남구 헌릉로 731,SK에너지,Y,Y,NaN
3,서울특별시,서울,강남구,GS칼텍스(주)직영 산성주유소,서울 강남구 헌릉로 730,서울 강남구 헌릉로 730,GS칼텍스,Y,Y,NaN
4,서울특별시,서울,강남구,방죽주유소,서울 강남구 밤고개로 215 (율현동),서울 강남구 밤고개로 215,S-OIL,Y,Y,NaN
6,서울특별시,서울,강남구,자곡셀프주유소,서울 강남구 밤고개로 120 (자곡동),서울 강남구 밤고개로 120,SK에너지,Y,Y,NaN
8,서울특별시,서울,강남구,SK서광주유소,서울 강남구 역삼로 142 (역삼동),서울 강남구 역삼로 142,SK에너지,Y,Y,NaN
...,...,...,...,...,...,...,...,...,...,...
7601,경상남도,경남,밀양,(주)천하주유소,경남 밀양 부북면 제대2길 14,경남 밀양 부북면 제대2길 14,S-OIL,N,Y,NaN
7602,경상남도,경남,창원시,광신직영(호원셀프),경남 창원시 마산회원구 내서읍 호원로 141,경남 창원시 마산회원구 내서읍 호원로 141,현대오일뱅크,Y,Y,NaN
7603,경상남도,경남,창원시,광신직영(호원셀프),경남 창원시 마산회원구 내서읍 호원로 141,경남 창원시 마산회원구 내서읍 호원로 141,현대오일뱅크,Y,Y,NaN
7604,경상남도,경남,함안군,영동주유소,경남 함안군 산인면 함마대로 1834,경남 함안군 산인면 함마대로 1834,S-OIL,N,Y,NaN
7605,제주특별자치도,제주,제주시,창성주유소,제주 제주시 노형로 315 (노형동),제주 제주시 노형로 315,GS칼텍스,N,Y,NaN

In [54]:
# import os
# path_dir = 'C:/Users/Sung/Desktop/Opinet_Data/주유소_부가정보'
# file_list = os.listdir(path_dir)
# len_file = len(file_list)
# csv_path = list()

# for i in range(len_file):
#     path =  path_dir +"\\" + file_list[i]
#     csv_path.append(path)

# tmp_raw = []
# for file_name in csv_path:
#     tmp = pd.read_csv(file_name, encoding="cp949") # header 는 3번째 줄에 있음 
#     tmp_raw.append(tmp)

# station_raw = pd.concat(tmp_raw)

['C:/Users/Sung/Desktop/Opinet_Data/주유소_부가정보\\all247.csv',
 'C:/Users/Sung/Desktop/Opinet_Data/주유소_부가정보\\carwash.csv',
 'C:/Users/Sung/Desktop/Opinet_Data/주유소_부가정보\\conv_store.csv',
 'C:/Users/Sung/Desktop/Opinet_Data/주유소_부가정보\\repair.csv']

In [69]:
dup_check = station_raw[station_raw["new_adr"].duplicated()]
dup_check.sort_values(by= "new_adr")

,Unnamed: 0,sido,si,gu,os_nm,new_adr,api_adr,poll_div_cd,self_yn,wash_yn,repair_yn,conv_yn,all24_yn,oil_price
3393,3393,경기도,경기,용인시,동일석유(주)초당주유소,경기 용인시 기흥구 동백죽전대로 179 (중동 1039),경기 용인시 기흥구 동백죽전대로 179,SK에너지,Y,Y,N,N,N,1398.0
751,751,경기도,경기,용인시,동일석유(주)초당주유소,경기 용인시 기흥구 동백죽전대로 179 (중동 1039),경기 용인시 기흥구 동백죽전대로 179,SK에너지,Y,N,Y,N,N,1398.0
729,729,경기도,경기,용인시,동일석유(주)초당주유소,경기 용인시 기흥구 동백죽전대로 179 (중동 1039),경기 용인시 기흥구 동백죽전대로 179,SK에너지,Y,N,Y,N,N,1398.0
218,218,경기도,경기,고양시,SK화정주유소,경기도 고양시 덕양구 호국로 430,경기도 고양시 덕양구 호국로 430,SK에너지,N,N,N,Y,N,1296.0
1713,1713,경기도,경기,고양시,SK화정주유소,경기도 고양시 덕양구 호국로 430,경기도 고양시 덕양구 호국로 430,SK에너지,N,Y,N,N,N,1296.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1251,1251,충청북도,충북,청주시,통일에너지,충청북도 청주시 서원구 청남로 2145(모충동),충청북도 청주시 서원구 청남로 2145,S-OIL,Y,N,N,N,Y,1329.0
4656,4656,충청북도,충북,청주시,통일에너지,충청북도 청주시 서원구 청남로 2145(모충동),충청북도 청주시 서원구 청남로 2145,S-OIL,Y,Y,N,N,N,1329.0
4778,4778,충청북도,충북,청주시,새터주유소,충청북도 청주시 청원구 새터로 203,충청북도 청주시 청원구 새터로 203,SK에너지,Y,Y,N,N,N,1339.0
4779,4779,충청북도,충북,청주시,(주)행복주유소충전소,충청북도 청주시 청원구 충청대로 258 (주성동),충청북도 청주시 청원구 충청대로 258,현대오일뱅크,Y,Y,N,N,N,1349.0
966,966,충청북도,충북,충주시,화령개발(주)공단주유소,충청북도 충주시 국원대로 370 (목행동),충청북도 충주시 국원대로 370,SK에너지,N,N,Y,N,N,1369.0