# 데이터 정리

## 편의점 데이터 합치기

In [2]:
import pandas as pd 
from glob import glob # 파일 경로를 쉽게 접근할 수 있게 해주는 모듈

In [4]:
# /data 폴더 안에  # 지역으로 시작하는 # xls 파일 전체를 의미 
glob("C:/Users/Sung/Desktop/Opinet_Data/편의점/지역*.xls")

['C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (1).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (10).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (100).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (11).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (12).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (13).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (14).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (15).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (16).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (17).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (18).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (19).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (2).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (20).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (21).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (22).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (23).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (24).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (25).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (26).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (27).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (28).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (29).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (3).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (30).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (31).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (32).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (33).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (34).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (35).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (36).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (37).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (38).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (39).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (4).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (40).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (41).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (42).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (43).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (44).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (45).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (46).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (47).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (48).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (49).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (5).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (50).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (51).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (52).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (53).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (54).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (55).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (56).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (57).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (58).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (59).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (6).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (60).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (61).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (62).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (63).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (64).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (65).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (66).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (67).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (68).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (69).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (7).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (70).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (71).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (72).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (73).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (74).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (75).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (76).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (77).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (78).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (79).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (8).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (80).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (81).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (82).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (83).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (84).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (85).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (86).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (87).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (88).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (89).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (9).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (90).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (91).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (92).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (93).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (94).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (95).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (96).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (97).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (98).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (99).xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150245.780.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150250.795.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150255.836.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150301.424.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150306.976.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150312.593.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150317.695.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150322.684.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150328.227.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150333.216.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150338.962.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150343.953.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150349.489.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150355.101.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150400.664.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150405.630.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150411.432.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150417.026.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150422.137.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150427.480.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150432.406.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150437.666.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150445.344.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150450.181.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150455.709.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150500.629.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150506.122.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150511.887.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150517.449.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150523.279.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150528.186.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150533.146.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150538.693.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150544.215.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150549.802.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150555.321.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150600.851.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150606.440.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150611.958.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150617.455.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150625.029.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150629.967.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150635.488.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150640.433.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150645.977.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150651.003.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150656.607.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150702.106.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150707.691.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150713.293.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150719.429.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150724.906.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150730.565.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150735.477.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150741.093.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150748.721.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150754.920.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150759.492.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150805.268.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150810.870.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150815.905.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150820.844.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150825.814.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150831.295.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150836.296.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150841.376.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150846.538.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150852.164.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150857.705.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150903.263.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150908.755.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150914.528.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150919.451.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150926.447.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150931.590.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150936.522.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150942.022.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150947.492.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150952.454.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T150957.960.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151002.956.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151007.959.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151013.506.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151019.767.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151025.371.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151030.369.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151035.298.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151040.834.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151046.417.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151053.349.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151058.953.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151104.513.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151109.998.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151115.563.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151120.519.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151126.031.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151131.603.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151136.503.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151142.064.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151147.623.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151153.141.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151158.722.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151204.232.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151209.721.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151215.252.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151220.221.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151225.793.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151231.389.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151236.248.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151241.787.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151247.371.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151254.947.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151300.555.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151306.062.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151311.630.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151317.125.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151322.654.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151328.176.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151333.214.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151338.189.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151343.756.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151349.308.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151354.882.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151400.579.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151406.754.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151411.750.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151416.666.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151422.219.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151427.222.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151432.951.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151438.500.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151443.989.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151449.617.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151454.647.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151459.601.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151504.591.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151512.263.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151517.810.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151523.382.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151528.992.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151534.717.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151539.406.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151544.908.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151549.848.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151555.403.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151600.935.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151606.505.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151612.027.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151617.646.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151622.695.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151628.185.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151633.772.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151639.245.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151644.204.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151649.180.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151654.905.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151659.715.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151705.206.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151710.103.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151717.702.xls',
 'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) - 2020-10-18T151722.693.xls']

In [6]:
# station_files 변수에 각 엑셀 파일의 경로와 이름을 리스트로 저장 
station_files = glob("C:/Users/Sung/Desktop/Opinet_Data/편의점/지역*.xls")
len(station_files)

261

In [7]:
station_files[0]

'C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (1).xls'

In [8]:
# 파일 한개 가져오기 
tmp_raw = []
tmp = pd.read_excel('C:/Users/Sung/Desktop/Opinet_Data/편의점\\지역_위치별(주유소) (1).xls', header = 2) # header 는 3번째 줄에 있음 
tmp_raw.append(tmp)
tmp_raw

[      지역               상호                     주소      상표         전화번호 셀프여부  \
 0  서울특별시  현대오일뱅크㈜직영 오천주유소  서울 강남구 봉은사로 503 (삼성동)  현대오일뱅크  02-545-2822    N
 1  서울특별시          뉴서울(강남)   서울 강남구 언주로 716 (논현동)   SK에너지  02-518-5631    N

    고급휘발유   휘발유    경유  실내등유
 0   1597  1441  1266  1025
 1   2330  2025  1865     -  ]

In [9]:
# 파일 여러개 가져오기
# read_excel 로 각 파일을 읽은 후
# tmp_raw 변수에 append
# 반복문 끝나면 pd.concat 명령으로 쉽게 하나로 합침
# 25개 엑셀 파일 하나로 합침

tmp_raw = []
for file_name in station_files:
    tmp = pd.read_excel(file_name, header = 2) # header 는 3번째 줄에 있음 
    tmp_raw.append(tmp)

station_raw = pd.concat(tmp_raw)

In [10]:
station_raw.info() # 가격 정보가 숫자형(int, float) 아니어서 나중에 처리해야 함

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1237 entries, 0 to 9
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      1237 non-null   object
 1   상호      1237 non-null   object
 2   주소      1237 non-null   object
 3   상표      1237 non-null   object
 4   전화번호    1237 non-null   object
 5   셀프여부    1237 non-null   object
 6   고급휘발유   1237 non-null   object
 7   휘발유     1237 non-null   object
 8   경유      1237 non-null   object
 9   실내등유    1237 non-null   object
dtypes: object(10)
memory usage: 106.3+ KB

In [12]:
station_raw.head()

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,서울특별시,현대오일뱅크㈜직영 오천주유소,서울 강남구 봉은사로 503 (삼성동),현대오일뱅크,02-545-2822,N,1597,1441,1266,1025
1,서울특별시,뉴서울(강남),서울 강남구 언주로 716 (논현동),SK에너지,02-518-5631,N,2330,2025,1865,-
0,경기도,현대오일뱅크㈜직영 안산공원셀프주유소,경기 안산시 단원구 광덕1로 268 (고잔동),현대오일뱅크,031-413-5051,Y,1535,1325,1125,-
1,경기도,(주)동강석유 남안산IC주유소,경기 안산시 단원구 성곡로 279 (신길동),S-OIL,031-494-1080,Y,-,1328,1128,860
2,경기도,반월공단주유소,경기 안산시 단원구 시우로 46,SK에너지,031-493-5182,Y,-,1378,1178,-

In [13]:
station_raw.tail()

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
5,제주특별자치도,삼화석유(주)천마주유소,제주 제주시 임항로 94 (건입동),SK에너지,064-753-8866,N,-,1400,1180,730
6,제주특별자치도,삼화석유(주)행복날개주유소,제주 제주시 용문로 12 (용담이동),SK에너지,064-711-5184,N,-,1400,1180,730
7,제주특별자치도,내트럭(주)제주사업소,제주 제주시 번영로 345,SK에너지,064-756-3005,N,-,1400,1180,-
8,제주특별자치도,(주)무수천주유소,제주 제주시 노형로 45,GS칼텍스,064-748-1515,N,-,1400,1180,730
9,제주특별자치도,삼광주유소,제주특별자치도 제주시 번영로 158 (화북이동),GS칼텍스,064-725-5188,N,-,1400,1135,730

In [14]:
# 원하는 컬럼 가지고 오고 이름도 다시 정의 stations 라는 변수에 저장 
# 지역, 상호, 주소, 상표, 셀프여부 
stations = pd.DataFrame({"sido" : station_raw["지역"],
                         "os_nm": station_raw["상호"],
                         "new_adr": station_raw["주소"],
                         "oil_price": station_raw["휘발유"],
                         "poll_div_cd": station_raw["상표"],
                         "self_yn": station_raw["셀프여부"]})
stations.head()

,sido,os_nm,new_adr,oil_price,poll_div_cd,self_yn
0,서울특별시,현대오일뱅크㈜직영 오천주유소,서울 강남구 봉은사로 503 (삼성동),1441,현대오일뱅크,N
1,서울특별시,뉴서울(강남),서울 강남구 언주로 716 (논현동),2025,SK에너지,N
0,경기도,현대오일뱅크㈜직영 안산공원셀프주유소,경기 안산시 단원구 광덕1로 268 (고잔동),1325,현대오일뱅크,Y
1,경기도,(주)동강석유 남안산IC주유소,경기 안산시 단원구 성곡로 279 (신길동),1328,S-OIL,Y
2,경기도,반월공단주유소,경기 안산시 단원구 시우로 46,1378,SK에너지,Y

## 주소-> 시/구로 쪼개기

In [15]:
eachAddress = "서울 강남구 현릉로 731(세곡동)"
eachAddress.split("(")

['서울 강남구 현릉로 731', '세곡동)']

In [16]:
eachAddress = "서울 강남구 현릉로 731(세곡동)"
eachAddress.split(" ")

['서울', '강남구', '현릉로', '731(세곡동)']

In [17]:
eachAddress = "서울 강남구 현릉로 731(세곡동)"
eachAddress.split()[0]

'서울'

In [18]:
# 구 이름 추출 
stations['si']  = [eachAddress.split()[0] for eachAddress in stations["new_adr"]] 
stations.head()

,sido,os_nm,new_adr,oil_price,poll_div_cd,self_yn,si
0,서울특별시,현대오일뱅크㈜직영 오천주유소,서울 강남구 봉은사로 503 (삼성동),1441,현대오일뱅크,N,서울
1,서울특별시,뉴서울(강남),서울 강남구 언주로 716 (논현동),2025,SK에너지,N,서울
0,경기도,현대오일뱅크㈜직영 안산공원셀프주유소,경기 안산시 단원구 광덕1로 268 (고잔동),1325,현대오일뱅크,Y,경기
1,경기도,(주)동강석유 남안산IC주유소,경기 안산시 단원구 성곡로 279 (신길동),1328,S-OIL,Y,경기
2,경기도,반월공단주유소,경기 안산시 단원구 시우로 46,1378,SK에너지,Y,경기

In [19]:
# 구 이름 추출 
stations['gu']  = [eachAddress.split()[1] for eachAddress in stations["new_adr"]] 
stations.head()

,sido,os_nm,new_adr,oil_price,poll_div_cd,self_yn,si,gu
0,서울특별시,현대오일뱅크㈜직영 오천주유소,서울 강남구 봉은사로 503 (삼성동),1441,현대오일뱅크,N,서울,강남구
1,서울특별시,뉴서울(강남),서울 강남구 언주로 716 (논현동),2025,SK에너지,N,서울,강남구
0,경기도,현대오일뱅크㈜직영 안산공원셀프주유소,경기 안산시 단원구 광덕1로 268 (고잔동),1325,현대오일뱅크,Y,경기,안산시
1,경기도,(주)동강석유 남안산IC주유소,경기 안산시 단원구 성곡로 279 (신길동),1328,S-OIL,Y,경기,안산시
2,경기도,반월공단주유소,경기 안산시 단원구 시우로 46,1378,SK에너지,Y,경기,안산시

In [20]:
# unique() 검사 
stations["si"].unique() # 잘 뽑혔는지 확인

array(['서울', '경기', '경기도', '부산', '부산광역시', '대구', '인천', '인천광역시', '광주', '대전',
       '대전광역시', '울산', '세종특별자치시', '세종시', '세종', '강원', '강원도', '충북', '충청북도',
       '충남', '충청남도', '전북', '전라북도', '전남', '전라남도', '경북', '경상북도', '경남',
       '경상남도', '제주', '제주특별자치도'], dtype=object)

In [21]:
stations.loc[stations["si"] == "광주시"]

Empty DataFrame
Columns: [sido, os_nm, new_adr, oil_price, poll_div_cd, self_yn, si, gu]
Index: []

In [62]:
stations.loc[stations["si"] == "세종시"]

,sido,os_nm,new_adr,oil_price,poll_div_cd,self_yn,si,gu
7,세종특별자치시,봉암주유소,세종시 연서면 세종로 1899,1269,SK에너지,Y,세종시,연서면
8,세종특별자치시,새롬주유소,세종시 어울로 77 (새롬동),1269,SK에너지,Y,세종시,어울로
24,세종특별자치시,㈜비타민셀프 세종셀프주유소,세종시 다정북로 221,1395,S-OIL,Y,세종시,다정북로
28,세종특별자치시,(주)한유에너지 중부주유소,세종시 조치원읍 세종로 2167,1499,SK에너지,N,세종시,조치원읍

In [22]:
stations.loc[stations["si"] == "청남"]

Empty DataFrame
Columns: [sido, os_nm, new_adr, oil_price, poll_div_cd, self_yn, si, gu]
Index: []

In [23]:
stations.loc[stations["si"] == "서울특별시"]

Empty DataFrame
Columns: [sido, os_nm, new_adr, oil_price, poll_div_cd, self_yn, si, gu]
Index: []

In [24]:
stations.loc[stations["si"] == "서울특별시", "si"] = "서울"
stations.loc[stations["si"] == "경기도", "si"] = "경기"
stations.loc[stations["si"] == "부산광역시", "si"] = "부산"
stations.loc[stations["si"] == "대구광역시", "si"] = "대구"

stations.loc[stations["si"] == "인천광역시", "si"] = "인천"
stations.loc[stations["si"] == "광주광역시", "si"] = "광주"
stations.loc[stations["si"] == "광주시", "si"] = "광주"

stations.loc[stations["si"] == "대전광역시", "si"] = "대전"
stations.loc[stations["si"] == "울산광역시", "si"] = "울산"
stations.loc[stations["si"] == "세종특별자치시", "si"] = "세종"
stations.loc[stations["si"] == "세종시", "si"] = "세종"

stations.loc[stations["si"] == "강원도", "si"] = "강원"
stations.loc[stations["si"] == "충청북도", "si"] = "충북"
stations.loc[stations["si"] == "충청남도", "si"] = "충남"
stations.loc[stations["si"] == "청남", "si"] = "충남"

stations.loc[stations["si"] == "전라북도", "si"] = "전북"
stations.loc[stations["si"] == "전라남도", "si"] = "전남"
stations.loc[stations["si"] == "경상북도", "si"] = "경북"
stations.loc[stations["si"] == "경상남도", "si"] = "경남"
stations.loc[stations["si"] == "제주특별자치도", "si"] = "제주"
stations.loc[stations["si"] == "제주도", "si"] = "제주"

In [25]:
# unique() 검사 
stations["si"].unique() # 잘 뽑혔는지 확인

array(['서울', '경기', '부산', '대구', '인천', '광주', '대전', '울산', '세종', '강원', '충북',
       '충남', '전북', '전남', '경북', '경남', '제주'], dtype=object)

In [26]:
len(stations["si"].unique())

17

In [27]:
# unique() 검사 
stations["gu"].unique() # 잘 뽑혔는지 확인

array(['강남구', '안산시', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구',
       '양천구', '영등포구', '강동구', '용산구', '종로구', '중랑구', '강서구', '금정구', '기장군',
       '남구', '강북구', '동래구', '부산진구', '북구', '사상구', '사하구', '영도구', '관악구',
       '해운대구', '달서구', '달성군', '동구', '서구', '수성구', '강화군', '계양구', '남동구',
       '미추홀구', '부평구', '연수구', '중구', '광산구', '구로구', '대덕구', '유성구', '금천구',
       '울주군', '세종로', '연서면', '조치원읍', '소정면', '전의면', '가평군', '고양시', '노원구',
       '광명시', '광주시', '구리시', '군포시', '김포시', '남양주시', '부천시', '성남시', '도봉구',
       '수원시', '시흥시', '안성시', '안양시', '양주시', '양평군', '여주시', '연천군', '오산시',
       '용인시', '의왕시', '의정부시', '이천시', '파주시', '평택시', '포천시', '하남시', '화성시',
       '강릉시', '고성군', '동해시', '삼척시', '속초시', '양양군', '영월군', '원주시', '인제군',
       '정선군', '춘천시', '태백시', '평창군', '홍천군', '화천군', '횡성군', '괴산군', '단양군',
       '보은군', '영동군', '옥천군', '음성군', '제천시', '증평군', '진천군', '청주시', '충주시',
       '공주시', '금산군', '논산시', '당진시', '보령시', '부여군', '서산시', '아산시', '예산군',
       '천안시', '청양군', '태안군', '홍성군', '고창군', '군산시', '김제시', '남원시', '무주군',
       '부안군', '완주군', '익산시', '임실군', '장수군', '전주시', '정읍시', '진안군', '강진군',
       '고흥군', '곡성군', '구례군', '나주시', '담양군', '목포시', '무안군', '보성군', '순천시',
       '신안군', '여수시', '영광군', '영암군', '완도군', '장성군', '장흥군', '진도군', '함평군',
       '해남군', '화순군', '경산시', '경주시', '고령군', '구미시', '군위군', '김천시', '문경시',
       '봉화군', '상주시', '성주군', '안동시', '영덕군', '영주시', '영천시', '예천군', '울진군',
       '의성군', '청도군', '청송군', '칠곡군', '포항시', '거제시', '거창군', '김해시', '밀양시',
       '산청군', '양산시', '진주시', '창녕군', '창원시', '통영시', '하동군', '함안군', '함양군',
       '합천군', '서귀포시', '제주시', '구좌읍'], dtype=object)

## 가격 정보 전처리

In [28]:
stations[stations["oil_price"] == "-"]

,sido,os_nm,new_adr,oil_price,poll_div_cd,self_yn,si,gu
5,울산광역시,새한주유소,울산 북구 효암로 84-1 (명촌동),-,현대오일뱅크,N,울산,북구
9,경기도,북한강주유소,경기 남양주시 화도읍 경춘로 2681,-,SK에너지,N,경기,남양주시
30,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),-,SK에너지,Y,경기,용인시
2,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),-,SK에너지,Y,경기,용인시
19,경기도,오성주유소,경기 평택시 안중읍 서동대로 1924,-,SK에너지,N,경기,평택시
4,강원도,한계령주유소,강원도 양양군 설악로 1556(서면),-,SK에너지,N,강원,양양군
3,강원도,재산주유소,강원 평창군 용평면 평창대로 1737,-,SK에너지,N,강원,평창군
7,충청북도,화양동주유소,충북 괴산군 청천면 화양로 578,-,자가상표,N,충북,괴산군
4,충청북도,천봉주유소,충북 보은군 보은읍 남부로 5084,-,GS칼텍스,Y,충북,보은군
18,충청북도,(주)청주관문주유소,충북 청주시 서원구 청남로 1894 (미평동),-,알뜰주유소,Y,충북,청주시
2,충청북도,(주)청주관문주유소,충북 청주시 서원구 청남로 1894 (미평동),-,알뜰주유소,Y,충북,청주시
16,충청북도,대촌주유소,충북 충주시 앙성면 가곡로 1702,-,현대오일뱅크,N,충북,충주시
12,충청남도,수운주유소,충남 당진시 정미면 서해로 4909,-,SK에너지,N,충남,당진시
5,경상북도,병곡주유소,경북 영덕군 병곡면 흰돌로 20,-,자가상표,N,경북,영덕군
14,경상북도,동진주유소,경북 포항시 북구 청하면 비학로 1515,-,S-OIL,N,경북,포항시
7,경상북도,동진주유소,경북 포항시 북구 청하면 비학로 1515,-,S-OIL,N,경북,포항시
11,경상남도,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,-,SK에너지,N,경남,창원시
2,경상남도,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,-,SK에너지,N,경남,창원시

In [29]:
# * 2. 정보가 기입되지 않은 주유소는 대상에서 제외 
stations_notnull = stations[stations["oil_price"] != '-']
stations_notnull.head()
stations_notnull["oil_price"] = [float(value) for value in stations_notnull["oil_price"]]
stations_notnull.info() # 가격 정보가 float 으로 바뀜\
stations_notnull.reset_index(inplace = True) # 인덱스를 처음부터 다시 기록하도록 함 
del stations_notnull["index"] # index 라는 컬럼이 하나 더 생성되어, 그 부분 제거

# 구별로 가격 평균 구하기 
import numpy as np 
si_gu_data =pd.pivot_table(stations_notnull, index =["si","gu"] , values = ["oil_price"],aggfunc = np.mean)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1219 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sido         1219 non-null   object
 1   os_nm        1219 non-null   object
 2   new_adr      1219 non-null   object
 3   oil_price    1219 non-null   float64
 4   poll_div_cd  1219 non-null   object
 5   self_yn      1219 non-null   object
 6   si           1219 non-null   object
 7   gu           1219 non-null   object
dtypes: float64(1), object(7)
memory usage: 85.7+ KB

<ipython-input-29-fcde174fa93a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations_notnull["oil_price"] = [float(value) for value in stations_notnull["oil_price"]]

In [30]:
si_gu_data.reset_index(inplace = True) # 인덱스를 처음부터 다시 기록하도록 함

In [31]:
si_gu_data

     si   gu    oil_price
0    강원  강릉시  1322.142857
1    강원  고성군  1324.000000
2    강원  동해시  1330.000000
3    강원  삼척시  1365.000000
4    강원  속초시  1379.000000
..   ..  ...          ...
201  충북  제천시  1315.000000
202  충북  증평군  1294.000000
203  충북  진천군  1353.166667
204  충북  청주시  1336.944444
205  충북  충주시  1304.250000

[206 rows x 3 columns]

In [32]:
stations_null = stations[stations["oil_price"]== '-']
stations_null.head()

,sido,os_nm,new_adr,oil_price,poll_div_cd,self_yn,si,gu
5,울산광역시,새한주유소,울산 북구 효암로 84-1 (명촌동),-,현대오일뱅크,N,울산,북구
9,경기도,북한강주유소,경기 남양주시 화도읍 경춘로 2681,-,SK에너지,N,경기,남양주시
30,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),-,SK에너지,Y,경기,용인시
2,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),-,SK에너지,Y,경기,용인시
19,경기도,오성주유소,경기 평택시 안중읍 서동대로 1924,-,SK에너지,N,경기,평택시

In [33]:
len(stations_null)

18

In [34]:
stations_null_tmp = pd.merge(stations_null, si_gu_data, how = "left", left_on = ["si","gu"], right_on = ["si","gu"])

In [35]:
stations_null_tmp

,sido,os_nm,new_adr,oil_price_x,poll_div_cd,self_yn,si,gu,oil_price_y
0,울산광역시,새한주유소,울산 북구 효암로 84-1 (명촌동),-,현대오일뱅크,N,울산,북구,1327.000000
1,경기도,북한강주유소,경기 남양주시 화도읍 경춘로 2681,-,SK에너지,N,경기,남양주시,1336.666667
2,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),-,SK에너지,Y,경기,용인시,1348.033333
3,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),-,SK에너지,Y,경기,용인시,1348.033333
4,경기도,오성주유소,경기 평택시 안중읍 서동대로 1924,-,SK에너지,N,경기,평택시,1331.421053
5,강원도,한계령주유소,강원도 양양군 설악로 1556(서면),-,SK에너지,N,강원,양양군,1363.000000
6,강원도,재산주유소,강원 평창군 용평면 평창대로 1737,-,SK에너지,N,강원,평창군,1391.000000
7,충청북도,화양동주유소,충북 괴산군 청천면 화양로 578,-,자가상표,N,충북,괴산군,1339.857143
8,충청북도,천봉주유소,충북 보은군 보은읍 남부로 5084,-,GS칼텍스,Y,충북,보은군,1357.000000
9,충청북도,(주)청주관문주유소,충북 청주시 서원구 청남로 1894 (미평동),-,알뜰주유소,Y,충북,청주시,1336.944444
10,충청북도,(주)청주관문주유소,충북 청주시 서원구 청남로 1894 (미평동),-,알뜰주유소,Y,충북,청주시,1336.944444
11,충청북도,대촌주유소,충북 충주시 앙성면 가곡로 1702,-,현대오일뱅크,N,충북,충주시,1304.250000
12,충청남도,수운주유소,충남 당진시 정미면 서해로 4909,-,SK에너지,N,충남,당진시,1332.916667
13,경상북도,병곡주유소,경북 영덕군 병곡면 흰돌로 20,-,자가상표,N,경북,영덕군,1288.000000
14,경상북도,동진주유소,경북 포항시 북구 청하면 비학로 1515,-,S-OIL,N,경북,포항시,1294.785714
15,경상북도,동진주유소,경북 포항시 북구 청하면 비학로 1515,-,S-OIL,N,경북,포항시,1294.785714
16,경상남도,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,-,SK에너지,N,경남,창원시,1306.272727
17,경상남도,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,-,SK에너지,N,경남,창원시,1306.272727

In [36]:
stations_null_tmp[stations_null_tmp["oil_price_y"].isna()]

Empty DataFrame
Columns: [sido, os_nm, new_adr, oil_price_x, poll_div_cd, self_yn, si, gu, oil_price_y]
Index: []

In [37]:
del stations_null_tmp["oil_price_x"]
stations_null_tmp.rename(columns = {"oil_price_y": "oil_price"}, inplace = True)

In [38]:
stations_null_tmp

,sido,os_nm,new_adr,poll_div_cd,self_yn,si,gu,oil_price
0,울산광역시,새한주유소,울산 북구 효암로 84-1 (명촌동),현대오일뱅크,N,울산,북구,1327.000000
1,경기도,북한강주유소,경기 남양주시 화도읍 경춘로 2681,SK에너지,N,경기,남양주시,1336.666667
2,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),SK에너지,Y,경기,용인시,1348.033333
3,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),SK에너지,Y,경기,용인시,1348.033333
4,경기도,오성주유소,경기 평택시 안중읍 서동대로 1924,SK에너지,N,경기,평택시,1331.421053
5,강원도,한계령주유소,강원도 양양군 설악로 1556(서면),SK에너지,N,강원,양양군,1363.000000
6,강원도,재산주유소,강원 평창군 용평면 평창대로 1737,SK에너지,N,강원,평창군,1391.000000
7,충청북도,화양동주유소,충북 괴산군 청천면 화양로 578,자가상표,N,충북,괴산군,1339.857143
8,충청북도,천봉주유소,충북 보은군 보은읍 남부로 5084,GS칼텍스,Y,충북,보은군,1357.000000
9,충청북도,(주)청주관문주유소,충북 청주시 서원구 청남로 1894 (미평동),알뜰주유소,Y,충북,청주시,1336.944444
10,충청북도,(주)청주관문주유소,충북 청주시 서원구 청남로 1894 (미평동),알뜰주유소,Y,충북,청주시,1336.944444
11,충청북도,대촌주유소,충북 충주시 앙성면 가곡로 1702,현대오일뱅크,N,충북,충주시,1304.250000
12,충청남도,수운주유소,충남 당진시 정미면 서해로 4909,SK에너지,N,충남,당진시,1332.916667
13,경상북도,병곡주유소,경북 영덕군 병곡면 흰돌로 20,자가상표,N,경북,영덕군,1288.000000
14,경상북도,동진주유소,경북 포항시 북구 청하면 비학로 1515,S-OIL,N,경북,포항시,1294.785714
15,경상북도,동진주유소,경북 포항시 북구 청하면 비학로 1515,S-OIL,N,경북,포항시,1294.785714
16,경상남도,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,SK에너지,N,경남,창원시,1306.272727
17,경상남도,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,SK에너지,N,경남,창원시,1306.272727

## 가격 정보 합치기

In [39]:
stations_null_tmp

,sido,os_nm,new_adr,poll_div_cd,self_yn,si,gu,oil_price
0,울산광역시,새한주유소,울산 북구 효암로 84-1 (명촌동),현대오일뱅크,N,울산,북구,1327.000000
1,경기도,북한강주유소,경기 남양주시 화도읍 경춘로 2681,SK에너지,N,경기,남양주시,1336.666667
2,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),SK에너지,Y,경기,용인시,1348.033333
3,경기도,(주)대지산주유소,경기 용인시 수지구 대지로 92 (죽전동),SK에너지,Y,경기,용인시,1348.033333
4,경기도,오성주유소,경기 평택시 안중읍 서동대로 1924,SK에너지,N,경기,평택시,1331.421053
5,강원도,한계령주유소,강원도 양양군 설악로 1556(서면),SK에너지,N,강원,양양군,1363.000000
6,강원도,재산주유소,강원 평창군 용평면 평창대로 1737,SK에너지,N,강원,평창군,1391.000000
7,충청북도,화양동주유소,충북 괴산군 청천면 화양로 578,자가상표,N,충북,괴산군,1339.857143
8,충청북도,천봉주유소,충북 보은군 보은읍 남부로 5084,GS칼텍스,Y,충북,보은군,1357.000000
9,충청북도,(주)청주관문주유소,충북 청주시 서원구 청남로 1894 (미평동),알뜰주유소,Y,충북,청주시,1336.944444
10,충청북도,(주)청주관문주유소,충북 청주시 서원구 청남로 1894 (미평동),알뜰주유소,Y,충북,청주시,1336.944444
11,충청북도,대촌주유소,충북 충주시 앙성면 가곡로 1702,현대오일뱅크,N,충북,충주시,1304.250000
12,충청남도,수운주유소,충남 당진시 정미면 서해로 4909,SK에너지,N,충남,당진시,1332.916667
13,경상북도,병곡주유소,경북 영덕군 병곡면 흰돌로 20,자가상표,N,경북,영덕군,1288.000000
14,경상북도,동진주유소,경북 포항시 북구 청하면 비학로 1515,S-OIL,N,경북,포항시,1294.785714
15,경상북도,동진주유소,경북 포항시 북구 청하면 비학로 1515,S-OIL,N,경북,포항시,1294.785714
16,경상남도,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,SK에너지,N,경남,창원시,1306.272727
17,경상남도,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,SK에너지,N,경남,창원시,1306.272727

In [40]:
stations_notnull

,sido,os_nm,new_adr,oil_price,poll_div_cd,self_yn,si,gu
0,서울특별시,현대오일뱅크㈜직영 오천주유소,서울 강남구 봉은사로 503 (삼성동),1441.0,현대오일뱅크,N,서울,강남구
1,서울특별시,뉴서울(강남),서울 강남구 언주로 716 (논현동),2025.0,SK에너지,N,서울,강남구
2,경기도,현대오일뱅크㈜직영 안산공원셀프주유소,경기 안산시 단원구 광덕1로 268 (고잔동),1325.0,현대오일뱅크,Y,경기,안산시
3,경기도,(주)동강석유 남안산IC주유소,경기 안산시 단원구 성곡로 279 (신길동),1328.0,S-OIL,Y,경기,안산시
4,경기도,반월공단주유소,경기 안산시 단원구 시우로 46,1378.0,SK에너지,Y,경기,안산시
...,...,...,...,...,...,...,...,...
1214,제주특별자치도,삼화석유(주)천마주유소,제주 제주시 임항로 94 (건입동),1400.0,SK에너지,N,제주,제주시
1215,제주특별자치도,삼화석유(주)행복날개주유소,제주 제주시 용문로 12 (용담이동),1400.0,SK에너지,N,제주,제주시
1216,제주특별자치도,내트럭(주)제주사업소,제주 제주시 번영로 345,1400.0,SK에너지,N,제주,제주시
1217,제주특별자치도,(주)무수천주유소,제주 제주시 노형로 45,1400.0,GS칼텍스,N,제주,제주시
1218,제주특별자치도,삼광주유소,제주특별자치도 제주시 번영로 158 (화북이동),1400.0,GS칼텍스,N,제주,제주시

In [41]:
stations_notnull = stations_notnull.sort_index(axis=1)
stations_null_tmp = stations_null_tmp.sort_index(axis=1)

In [42]:
stations_notnull

,gu,new_adr,oil_price,os_nm,poll_div_cd,self_yn,si,sido
0,강남구,서울 강남구 봉은사로 503 (삼성동),1441.0,현대오일뱅크㈜직영 오천주유소,현대오일뱅크,N,서울,서울특별시
1,강남구,서울 강남구 언주로 716 (논현동),2025.0,뉴서울(강남),SK에너지,N,서울,서울특별시
2,안산시,경기 안산시 단원구 광덕1로 268 (고잔동),1325.0,현대오일뱅크㈜직영 안산공원셀프주유소,현대오일뱅크,Y,경기,경기도
3,안산시,경기 안산시 단원구 성곡로 279 (신길동),1328.0,(주)동강석유 남안산IC주유소,S-OIL,Y,경기,경기도
4,안산시,경기 안산시 단원구 시우로 46,1378.0,반월공단주유소,SK에너지,Y,경기,경기도
...,...,...,...,...,...,...,...,...
1214,제주시,제주 제주시 임항로 94 (건입동),1400.0,삼화석유(주)천마주유소,SK에너지,N,제주,제주특별자치도
1215,제주시,제주 제주시 용문로 12 (용담이동),1400.0,삼화석유(주)행복날개주유소,SK에너지,N,제주,제주특별자치도
1216,제주시,제주 제주시 번영로 345,1400.0,내트럭(주)제주사업소,SK에너지,N,제주,제주특별자치도
1217,제주시,제주 제주시 노형로 45,1400.0,(주)무수천주유소,GS칼텍스,N,제주,제주특별자치도
1218,제주시,제주특별자치도 제주시 번영로 158 (화북이동),1400.0,삼광주유소,GS칼텍스,N,제주,제주특별자치도

In [43]:
stations_null_tmp

,gu,new_adr,oil_price,os_nm,poll_div_cd,self_yn,si,sido
0,북구,울산 북구 효암로 84-1 (명촌동),1327.000000,새한주유소,현대오일뱅크,N,울산,울산광역시
1,남양주시,경기 남양주시 화도읍 경춘로 2681,1336.666667,북한강주유소,SK에너지,N,경기,경기도
2,용인시,경기 용인시 수지구 대지로 92 (죽전동),1348.033333,(주)대지산주유소,SK에너지,Y,경기,경기도
3,용인시,경기 용인시 수지구 대지로 92 (죽전동),1348.033333,(주)대지산주유소,SK에너지,Y,경기,경기도
4,평택시,경기 평택시 안중읍 서동대로 1924,1331.421053,오성주유소,SK에너지,N,경기,경기도
5,양양군,강원도 양양군 설악로 1556(서면),1363.000000,한계령주유소,SK에너지,N,강원,강원도
6,평창군,강원 평창군 용평면 평창대로 1737,1391.000000,재산주유소,SK에너지,N,강원,강원도
7,괴산군,충북 괴산군 청천면 화양로 578,1339.857143,화양동주유소,자가상표,N,충북,충청북도
8,보은군,충북 보은군 보은읍 남부로 5084,1357.000000,천봉주유소,GS칼텍스,Y,충북,충청북도
9,청주시,충북 청주시 서원구 청남로 1894 (미평동),1336.944444,(주)청주관문주유소,알뜰주유소,Y,충북,충청북도
10,청주시,충북 청주시 서원구 청남로 1894 (미평동),1336.944444,(주)청주관문주유소,알뜰주유소,Y,충북,충청북도
11,충주시,충북 충주시 앙성면 가곡로 1702,1304.250000,대촌주유소,현대오일뱅크,N,충북,충청북도
12,당진시,충남 당진시 정미면 서해로 4909,1332.916667,수운주유소,SK에너지,N,충남,충청남도
13,영덕군,경북 영덕군 병곡면 흰돌로 20,1288.000000,병곡주유소,자가상표,N,경북,경상북도
14,포항시,경북 포항시 북구 청하면 비학로 1515,1294.785714,동진주유소,S-OIL,N,경북,경상북도
15,포항시,경북 포항시 북구 청하면 비학로 1515,1294.785714,동진주유소,S-OIL,N,경북,경상북도
16,창원시,경남 창원시 마산합포구 진동면 삼진의거대로 614,1306.272727,(주)삼진에너지,SK에너지,N,경남,경상남도
17,창원시,경남 창원시 마산합포구 진동면 삼진의거대로 614,1306.272727,(주)삼진에너지,SK에너지,N,경남,경상남도

In [44]:
stations_price = pd.concat([stations_notnull,stations_null_tmp], axis = 0)

In [45]:
stations_price

,gu,new_adr,oil_price,os_nm,poll_div_cd,self_yn,si,sido
0,강남구,서울 강남구 봉은사로 503 (삼성동),1441.000000,현대오일뱅크㈜직영 오천주유소,현대오일뱅크,N,서울,서울특별시
1,강남구,서울 강남구 언주로 716 (논현동),2025.000000,뉴서울(강남),SK에너지,N,서울,서울특별시
2,안산시,경기 안산시 단원구 광덕1로 268 (고잔동),1325.000000,현대오일뱅크㈜직영 안산공원셀프주유소,현대오일뱅크,Y,경기,경기도
3,안산시,경기 안산시 단원구 성곡로 279 (신길동),1328.000000,(주)동강석유 남안산IC주유소,S-OIL,Y,경기,경기도
4,안산시,경기 안산시 단원구 시우로 46,1378.000000,반월공단주유소,SK에너지,Y,경기,경기도
...,...,...,...,...,...,...,...,...
13,영덕군,경북 영덕군 병곡면 흰돌로 20,1288.000000,병곡주유소,자가상표,N,경북,경상북도
14,포항시,경북 포항시 북구 청하면 비학로 1515,1294.785714,동진주유소,S-OIL,N,경북,경상북도
15,포항시,경북 포항시 북구 청하면 비학로 1515,1294.785714,동진주유소,S-OIL,N,경북,경상북도
16,창원시,경남 창원시 마산합포구 진동면 삼진의거대로 614,1306.272727,(주)삼진에너지,SK에너지,N,경남,경상남도
17,창원시,경남 창원시 마산합포구 진동면 삼진의거대로 614,1306.272727,(주)삼진에너지,SK에너지,N,경남,경상남도

In [46]:
conv_store = stations_price.copy()

In [47]:
conv_store

,gu,new_adr,oil_price,os_nm,poll_div_cd,self_yn,si,sido
0,강남구,서울 강남구 봉은사로 503 (삼성동),1441.000000,현대오일뱅크㈜직영 오천주유소,현대오일뱅크,N,서울,서울특별시
1,강남구,서울 강남구 언주로 716 (논현동),2025.000000,뉴서울(강남),SK에너지,N,서울,서울특별시
2,안산시,경기 안산시 단원구 광덕1로 268 (고잔동),1325.000000,현대오일뱅크㈜직영 안산공원셀프주유소,현대오일뱅크,Y,경기,경기도
3,안산시,경기 안산시 단원구 성곡로 279 (신길동),1328.000000,(주)동강석유 남안산IC주유소,S-OIL,Y,경기,경기도
4,안산시,경기 안산시 단원구 시우로 46,1378.000000,반월공단주유소,SK에너지,Y,경기,경기도
...,...,...,...,...,...,...,...,...
13,영덕군,경북 영덕군 병곡면 흰돌로 20,1288.000000,병곡주유소,자가상표,N,경북,경상북도
14,포항시,경북 포항시 북구 청하면 비학로 1515,1294.785714,동진주유소,S-OIL,N,경북,경상북도
15,포항시,경북 포항시 북구 청하면 비학로 1515,1294.785714,동진주유소,S-OIL,N,경북,경상북도
16,창원시,경남 창원시 마산합포구 진동면 삼진의거대로 614,1306.272727,(주)삼진에너지,SK에너지,N,경남,경상남도
17,창원시,경남 창원시 마산합포구 진동면 삼진의거대로 614,1306.272727,(주)삼진에너지,SK에너지,N,경남,경상남도

## 주소 바꾸기

In [55]:
conv_store['api_adr']  = [eachAddress.split("(")[0] for eachAddress in conv_store["new_adr"]]

In [56]:
conv_store["wash_yn"]= "N"
conv_store["repair_yn"] = "N"
conv_store["conv_yn"] = "Y"
conv_store["all24_yn"] = "N"

In [57]:
conv_store.columns

Index(['sido', 'si', 'gu', 'os_nm', 'new_adr', 'api_adr', 'poll_div_cd',
       'self_yn', 'wash_yn', 'repair_yn', 'conv_yn', 'all24_yn', 'oil_price'],
      dtype='object')

In [58]:
#['A', 'B', 'C'] <-this is your columns order
conv_store = conv_store[["sido", "si", "gu","os_nm","new_adr","api_adr","poll_div_cd",
                         "self_yn","wash_yn","repair_yn","conv_yn","all24_yn",
                         "oil_price"]]

In [60]:
conv_store

,sido,si,gu,os_nm,new_adr,api_adr,poll_div_cd,self_yn,wash_yn,repair_yn,conv_yn,all24_yn,oil_price
0,서울특별시,서울,강남구,현대오일뱅크㈜직영 오천주유소,서울 강남구 봉은사로 503 (삼성동),서울 강남구 봉은사로 503,현대오일뱅크,N,N,N,Y,N,1441.000000
1,서울특별시,서울,강남구,뉴서울(강남),서울 강남구 언주로 716 (논현동),서울 강남구 언주로 716,SK에너지,N,N,N,Y,N,2025.000000
2,경기도,경기,안산시,현대오일뱅크㈜직영 안산공원셀프주유소,경기 안산시 단원구 광덕1로 268 (고잔동),경기 안산시 단원구 광덕1로 268,현대오일뱅크,Y,N,N,Y,N,1325.000000
3,경기도,경기,안산시,(주)동강석유 남안산IC주유소,경기 안산시 단원구 성곡로 279 (신길동),경기 안산시 단원구 성곡로 279,S-OIL,Y,N,N,Y,N,1328.000000
4,경기도,경기,안산시,반월공단주유소,경기 안산시 단원구 시우로 46,경기 안산시 단원구 시우로 46,SK에너지,Y,N,N,Y,N,1378.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,경상북도,경북,영덕군,병곡주유소,경북 영덕군 병곡면 흰돌로 20,경북 영덕군 병곡면 흰돌로 20,자가상표,N,N,N,Y,N,1288.000000
14,경상북도,경북,포항시,동진주유소,경북 포항시 북구 청하면 비학로 1515,경북 포항시 북구 청하면 비학로 1515,S-OIL,N,N,N,Y,N,1294.785714
15,경상북도,경북,포항시,동진주유소,경북 포항시 북구 청하면 비학로 1515,경북 포항시 북구 청하면 비학로 1515,S-OIL,N,N,N,Y,N,1294.785714
16,경상남도,경남,창원시,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,경남 창원시 마산합포구 진동면 삼진의거대로 614,SK에너지,N,N,N,Y,N,1306.272727
17,경상남도,경남,창원시,(주)삼진에너지,경남 창원시 마산합포구 진동면 삼진의거대로 614,경남 창원시 마산합포구 진동면 삼진의거대로 614,SK에너지,N,N,N,Y,N,1306.272727

In [61]:
conv_store.to_csv('C:\\Users\\Sung\\Desktop\\Opinet_Data\\conv_store.csv',encoding = 'cp949')